robot_initial_pose:
  position:
    x: 0.7
    y: 0.5
    z: 0.0
  orientation:
    w: 1.0
    x: 0.0
    y: 0.0
    z: 0.0

robot_body_frame: "base_link"
hand_request_frame: "hand_request"

move_duration_initial: 0.5
move_duration_tracking: 0.1

disable_service: false
