initial_pose:
  position: &initial_position
    x: 0.7
    y: 0.0
    z: 0.5
  orientation:
    w: 1.0
    x: 0.0
    y: 0.0
    z: 0.0

body_frame: "base_link"
hand_request_frame: "hand_request"
odom_frame: "odom"
body_origin_frame: "body_origin"

move_duration_initial: 0.5
move_duration_tracking: 0.1

spot_motion_mode: "TRANSLATION" # options: STATIC, MOTION
body_pose_method: "ACTION" # options: TOPIC, ACTION

reset_on_start: true

hand_bbox:
  size:
    x: 0.4
    y: 0.4
    z: 0.4

# Currently used only in ROTATION mode, in degrees
angle_limits:
  roll:
    min: -180.0
    max: 180.0
  pitch:
    min: -180.0
    max: 180.0
  yaw:
    min: -180.0
    max: 180.0

spot_commands_enabled: false
